export const defaultTheme = {
  blackColor: "#333333",
  whiteColor: "#F6F6F6",
  lightBlueBackgroundColor: "#D8ECFE",
  lightGreenCardColor: "#E1EDCE",
  greenPanelColor: "#88AA4D",
  lightPinkCardColor: "#F8DDD7",
  redPanelColor: "#F75531",
  orangeButtonColor: "#FC9B27",
  orangeButtonHoverColor: "#FC7427",
  footerHeight: "80px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  fontWeightDefault: "400",
  lineHeightDefault: "150%",
  pageWidth: "1280px",
  indent: "24px",
  pagePadding: "90px",
}